name: github pages

on:
  push:
    branches:
      - master
      - next

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
      
      # Bust cache via ASSETS_DIR to fix https://github.com/gridsome/gridsome/issues/1032
      - run: |
          ASSETS_DIR=a-$(git rev-parse --short HEAD) \
          PATH_PREFIX=$([ "$GITHUB_REF" == refs/heads/next ] && echo /next)/ \
          npm run build
      - run: cp CNAME dist/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: next
